name: Docker ECR Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: ror-demo
      ECR_REPOSITORY: ror-demo
      EC2_INSTANCE_IP: 3.89.73.48
      EC2_INSTANCE_SSH_KEY: ${{ secrets.EC2_INSTANCE_SSH_KEY }}
      DOCKER_IMAGE_NAME: new-image
      DOCKER_TAG: ${{ github.sha }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build and Push Docker Image to ECR
      run: |
        docker build -t $DOCKER_IMAGE_NAME .
        docker tag $DOCKER_IMAGE_NAME $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG

    - name: Deploy Docker Image to EC2 Instance
      run: |
        scp -i $EC2_INSTANCE_SSH_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./ec2-deployment ubuntu@$EC2_INSTANCE_IP:/home/ubuntu/
        ssh -i $EC2_INSTANCE_SSH_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$EC2_INSTANCE_IP "cd /home/ubuntu/ec2-deployment && docker-compose up -d"

    - name: Cleanup
      run: |
        docker logout $ECR_REGISTRY
        # Any additional cleanup steps you may need
