name: Build and push image to ECR

on: push
  

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ror-demo
        IMAGE_TAG: sample_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Pull Docker image from ECR
      run: docker pull 048273253858.dkr.ecr.us-east-1.amazonaws.com/ror-demo:sample_image
    
    - name: Deploy to Ec2
      env:  
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ror-demo
        IMAGE_TAG: sample_image
        aws-region: us-east-1
      uses: appleboy/ssh-action@master
      with:
        host: 3.89.73.48
        username: ubuntu
        key: ${{secrets.EC2_INSTANCE_SSH_KEY}}
        script: |
          # sudo apt-get update
          # sudo apt-get install -y docker.io
          # sudo service docker start
          docker stop webapp || true
          docker rm webapp || true
          docker pull 048273253858.dkr.ecr.us-east-1.amazonaws.com/ror-demo:sample_image
          docker run -d --name ror-container -p 3000:3000 048273253858.dkr.ecr.us-east-1.amazonaws.com/ror-demo:sample_image
        
        


        
    # - name: Deploy to EC2
    #   run: |
    #     echo "$PRIVATE_KEY" > private_key.pem
    #     chmod 600 private_key.pem
    #     ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@3.89.73.48<< EOF
    #       docker stop ror-container || true
    #       docker rm ror-container || true
    #       docker pull 048273253858.dkr.ecr.us-east-1.amazonaws.com/ror-demo:sample_image
    #       docker run -d --name ror-container -p 3000:3000 048273253858.dkr.ecr.us-east-1.amazonaws.com/ror-demo:sample_image
          
    #   env:
    #     DOCKER_CLI_APS: "1"
    #     PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_SSH_KEY }}
