name: Build Push & Deploy

on:
  push:
    branches: ["feature_deploymwnt"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Send Slack message
      uses: slackapi/slack-github-action@v1.24.0
      with:
        text: "New Pull Request: #${{ github.event.pull_request.number }} opened by ${{ github.event.pull_request.user.login }}"
        channel: your_slack_channel
        # Additional configuration options for the Slack message
